### ISSUE TITLE
I want to solve a Timeout error. (Timed out waiting for a node assignment. Call: listNodes )

### ISSUE THREAD

**Issue by kokoji** [ibm-messaging/kafka-connect-jdbc-sink#43]
Hello,

I used db2 as the DB and ran it in standalone mode. When I ran the test, I got the following error.
I would like to solve this problem.
Do you have any links or information that can help me?
I am attaching a log file of the standard output when run in standalone mode.

```
[2022-01-12 02:49:42,263] ERROR Stopping due to error (org.apache.kafka.connect.cli.ConnectStandalone:126)
org.apache.kafka.connect.errors.ConnectException: Failed to connect to and describe Kafka cluster. Check worker's broker connection and security properties.
	at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:70)
	at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:51)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:82)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:165)
	at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:64)
	... 2 more
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes
```
[kafka_standalone_log.log](https://github.com/ibm-messaging/kafka-connect-jdbc-sink/files/7848916/kafka_standalone_log.log)

**Comment by kokoji** [comment]
Hi,

I did the same thing after restarting Kafka, zookeeper and rabbitmq-server, and the error message changed.

`[2022-01-12 03:15:11,340] ERROR [jdbc-sink-connector|task-0] com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=CREATE TABLE [schema].[table] (id INTEGER ;BEGIN-OF-STATEMENT;<select>, DRIVER=4.26.14 (com.ibm.eventstreams.connect.jdbcsink.JDBCSinkTask:151)
[2022-01-12 03:15:11,342] ERROR [jdbc-sink-connector|task-0] Write of 1 records failed, remainingRetries=0 (com.ibm.eventstreams.connect.jdbcsink.JDBCSinkTask:106)
com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=CREATE TABLE [schema].[table] (id INTEGER ;BEGIN-OF-STATEMENT;<select>, DRIVER=4.26.14
	at com.ibm.db2.jcc.am.b7.a(b7.java:810)
	at com.ibm.db2.jcc.am.b7.a(b7.java:66)
	at com.ibm.db2.jcc.am.b7.a(b7.java:140)
	at com.ibm.db2.jcc.am.k4.c(k4.java:2824)
	at com.ibm.db2.jcc.am.k4.d(k4.java:2808)
	at com.ibm.db2.jcc.am.k4.b(k4.java:2168)
	at com.ibm.db2.jcc.t4.ab.k(ab.java:446)
	at com.ibm.db2.jcc.t4.ab.c(ab.java:104)
	at com.ibm.db2.jcc.t4.p.b(p.java:38)
	at com.ibm.db2.jcc.t4.av.h(av.java:124)
	at com.ibm.db2.jcc.am.k4.ak(k4.java:2163)
	at com.ibm.db2.jcc.am.k4.a(k4.java:3366)
	at com.ibm.db2.jcc.am.k4.e(k4.java:1131)
	at com.ibm.db2.jcc.am.k4.execute(k4.java:1110)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:1006)
	at com.ibm.eventstreams.connect.jdbcsink.database.writer.JDBCWriter.createTable(JDBCWriter.java:92)
	at com.ibm.eventstreams.connect.jdbcsink.database.writer.JDBCWriter.insert(JDBCWriter.java:113)
	at com.ibm.eventstreams.connect.jdbcsink.JDBCSinkTask.put(JDBCSinkTask.java:99)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:329)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:186)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:241)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

`
[kafka_standalone_log2.log](https://github.com/ibm-messaging/kafka-connect-jdbc-sink/files/7849012/kafka_standalone_log2.log)

**Comment by kokoji** [comment]
Hi,

I changed the parameter table.name.format in the jdbc-sink.properties file and ran it, and got the expected results.

Thank you!
